### ISSUE TITLE
Clean content command does not clean inside object fields

### ISSUE THREAD

**Issue by bezin** [getkirby/cli#90]
Hello all,

first of all thanks for the CLI and specifically the `clean:content` command. I use it regularly durcing development. I noticed, that it does not clean inside object fields – and probably also not inside structure fields, though I did not test this. 

To recreate: 
1. Add an object field to a blueprint, e.g. inside an page blueprint:
```
type: object
label:
  en: Project Details
  de: Projektdetails
fields:
  services:
    label:
      en: Services
      de: Leistungen
    type: tags
    icon: tag
    width: 1/2

  city:
    label:
      en: City
      de: Stadt
    type: text
    icon: pin
    width: 1/2
```
2. Add content to both fields of the object field. 
3. Remove one of the fields from the blueprint.
4. Run `clean:content` on the cli.

The content you removed is still stored inside the object field. I would expect it to be removed, too, as inside an object field are also just fields? Maybe there are side-effects I do not see at the moment, but it would be great if you could consider implementing this. During development object blueprints change as regularly as the general blueprints, so that would be really handy to clean up the mess :-)

Best
Benedict
